#!/bin/sh
# return "abs" if input path absolute and "rel" if input path relative
firstchar=`echo $1 | awk '{ print substr($0,1,1) }'`
secondchar=`echo $1 | awk '{ print substr($0,2,1) }'`
if [[ $firstchar = "/" || $secondchar = ":" ]]; then
    echo "abs"
else
    echo "rel"
fi
